"""ORM models.

Importing this package registers every table on ``Base.metadata``; Alembic's
``env.py`` relies on that for autogeneration, so new model modules must be
added here.
"""

from app.db.base import Base
from app.models.activities import (
    Activity,
    ActivityCost,
    ActivityEquipment,
    ActivityPermit,
    ActivityPhoto,
    ActivityPreparation,
)
from app.models.artifact import Artifact, artifact_materials, artifact_publications
from app.models.audit import ActivityLog, Comment, Notification, Revision
from app.models.context import ContextRelationship, ExcavationContext
from app.models.enums import (
    AcquisitionMethod,
    ActivityAction,
    ActivityKind,
    ActivityStatus,
    BudgetStatus,
    CalibrationResult,
    ConditionState,
    ConservationStatus,
    ContextType,
    DocumentType,
    EquipmentStatus,
    ExhibitionStatus,
    ExpenseCategory,
    ExpenseStatus,
    GeometryKind,
    ImportStatus,
    LayerCategory,
    LoanDirection,
    LoanStatus,
    Model3DFormat,
    Module,
    ModuleLevel,
    MovementReason,
    NotificationType,
    ObjectStatus,
    PermissionLevel,
    PermitStatus,
    PostKind,
    PostStatus,
    ProjectRole,
    ProjectStatus,
    ProtectionStatus,
    ResourceType,
    ReviewStatus,
    ShapeKind,
    SiteType,
    SocialPlatform,
    StockReason,
    StorageKind,
    StratigraphicRelation,
    TaskPriority,
    TaskStatus,
    TreatmentType,
    UserRole,
)
from app.models.floorplan import FloorPlan, FloorPlanShape
from app.models.gis import GisFeature, GisLayer
from app.models.imports import ImportBatch
from app.models.inventory import (
    Calibration,
    Checkout,
    Consumable,
    Equipment,
    Kit,
    KitTemplate,
    KitTemplateLine,
    StockMovement,
)
from app.models.management import Budget, CalendarEvent, Expense, Task
from app.models.media import Document, MediaFolder, MediaFolderKind, Model3D, Photograph
from app.models.museum import (
    Collection,
    ConservationRecord,
    EnvironmentalReading,
    Exhibition,
    ExhibitionItem,
    Loan,
    LoanItem,
    MuseumObject,
)
from app.models.project import Project, ProjectMembership
from app.models.site import Site
from app.models.social import PostAsset, PostMetric, SocialAccount, SocialPost
from app.models.storage import StorageLocation, StorageMovement
from app.models.taxonomy import Material, ObjectCategory, Period, Publication, SystemSetting
from app.models.user import RecordPermission, RefreshToken, User, UserModuleAccess

__all__ = [
    "Activity",
    "ActivityCost",
    "ActivityEquipment",
    "ActivityKind",
    "ActivityPermit",
    "ActivityPhoto",
    "ActivityPreparation",
    "ActivityStatus",
    "PermitStatus",
    "PostAsset",
    "PostKind",
    "PostMetric",
    "PostStatus",
    "SocialAccount",
    "SocialPlatform",
    "SocialPost",
    "Budget",
    "BudgetStatus",
    "CalendarEvent",
    "Expense",
    "ExpenseCategory",
    "ExpenseStatus",
    "Task",
    "TaskPriority",
    "TaskStatus",
    "Calibration",
    "CalibrationResult",
    "Checkout",
    "Consumable",
    "Equipment",
    "EquipmentStatus",
    "Kit",
    "KitTemplate",
    "KitTemplateLine",
    "StockMovement",
    "StockReason",
    "TreatmentType",
    "ObjectStatus",
    "MuseumObject",
    "LoanStatus",
    "LoanItem",
    "LoanDirection",
    "Loan",
    "ExhibitionStatus",
    "ExhibitionItem",
    "Exhibition",
    "EnvironmentalReading",
    "ConservationRecord",
    "Collection",
    "AcquisitionMethod",
    "ActivityAction",
    "ActivityLog",
    "Artifact",
    "Base",
    "Comment",
    "ConditionState",
    "ConservationStatus",
    "ContextRelationship",
    "ContextType",
    "Document",
    "DocumentType",
    "ExcavationContext",
    "GeometryKind",
    "GisFeature",
    "GisLayer",
    "LayerCategory",
    "Material",
    "MediaFolder",
    "MediaFolderKind",
    "Model3D",
    "Model3DFormat",
    "Notification",
    "NotificationType",
    "ObjectCategory",
    "Period",
    "PermissionLevel",
    "Photograph",
    "Project",
    "ProjectMembership",
    "ProjectRole",
    "ProjectStatus",
    "ProtectionStatus",
    "Publication",
    "Module",
    "ModuleLevel",
    "MovementReason",
    "RecordPermission",
    "RefreshToken",
    "ResourceType",
    "Revision",
    "ReviewStatus",
    "Site",
    "StorageKind",
    "StorageLocation",
    "FloorPlan",
    "FloorPlanShape",
    "ImportBatch",
    "ImportStatus",
    "ShapeKind",
    "StorageMovement",
    "SiteType",
    "StratigraphicRelation",
    "SystemSetting",
    "User",
    "UserModuleAccess",
    "UserRole",
    "artifact_materials",
    "artifact_publications",
]
