"""Record audit timestamps at append time.

Revision ID: 0004_audit_clock_timestamp
Revises: 0003_activity_project
Created: 2026-07-31 19:34:19.215895+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = "0004_audit_clock_timestamp"
down_revision: Union[str, None] = "0003_activity_project"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # now() is the transaction start time, so entries written by one request
    # all shared an instant and their relative order was undefined — which made
    # feed pagination unstable. clock_timestamp() is the real moment of append.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("clock_timestamp()"),
        existing_nullable=False,
    )
    op.alter_column(
        "revisions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("clock_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "revisions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "activity_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
