"""The activity hub: what we did, what it took, and what it cost.

Six tables and one column.

``activities`` is the undertaking — a season, a survey, a school visit — and
the five child tables are the answers to the questions asked six weeks before
doing it again: what we took, what we needed permission for, what had to be
arranged beforehand, what it cost, and what it looked like.

The column is ``calendar_events.activity_id``. That link is what turns the
shared calendar into the front door of the hub: pick a previous activity when
adding a day and the entry fills itself in from it.

Three things here are load-bearing:

- ``activity_costs.category`` **reuses** the ``expense_category`` type created
  by 0015 rather than declaring its own, so a cost recorded against an activity
  and an expense recorded against a budget land in the same bucket in a report.
  It is attached with ``create_type=False`` because the type already exists —
  autogenerate emits a fresh ``sa.Enum``, which tries to CREATE TYPE a second
  time and fails the migration.
- ``uq_activity_photos_cover`` is a *partial* unique index, so an activity has
  at most one cover photograph while still holding as many ordinary ones as it
  likes. A plain unique constraint on ``(activity_id, is_cover)`` would allow
  one cover and one non-cover, which is the opposite of the rule.
- Every existing non-administrator account is **granted the new module** at the
  bottom of the upgrade. The hub is shared by the institution, so an account
  that predates it must not have to wait for somebody to hand it over. This is
  why the enum values arrived in their own revision (0017): PostgreSQL refuses
  to let a value added to an enum be used in the same transaction.

Revision ID: 0018_activities
Revises: 0017_activity_module
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = "0018_activities"
down_revision: Union[str, None] = "0017_activity_module"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "excavation",
                "survey",
                "fieldwalking",
                "geophysics",
                "underwater",
                "recording",
                "conservation",
                "laboratory",
                "training",
                "outreach",
                "exhibition",
                "conference",
                "site_visit",
                "maintenance",
                "other",
                name="activity_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "approved",
                "in_progress",
                "completed",
                "postponed",
                "cancelled",
                name="activity_status",
            ),
            nullable=False,
        ),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("budget_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("lead_label", sa.String(length=200), nullable=True),
        sa.Column("team_size", sa.Integer(), nullable=True),
        sa.Column("team_notes", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("lessons", sa.Text(), nullable=True),
        sa.Column("repeated_from_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "starts_on IS NULL OR ends_on IS NULL OR ends_on >= starts_on",
            name=op.f("ck_activities_ck_activities_ends_after_starts"),
        ),
        sa.CheckConstraint(
            "team_size IS NULL OR team_size >= 0",
            name=op.f("ck_activities_ck_activities_team_size"),
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
            name=op.f("fk_activities_budget_id_budgets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["users.id"], name=op.f("fk_activities_lead_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_activities_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_activities_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["repeated_from_id"],
            ["activities.id"],
            name=op.f("fk_activities_repeated_from_id_activities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_activities_site_id_sites"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(op.f("ix_activities_budget_id"), "activities", ["budget_id"], unique=False)
    op.create_index(op.f("ix_activities_created_at"), "activities", ["created_at"], unique=False)
    op.create_index(op.f("ix_activities_ends_on"), "activities", ["ends_on"], unique=False)
    op.create_index(op.f("ix_activities_is_public"), "activities", ["is_public"], unique=False)
    op.create_index(op.f("ix_activities_kind"), "activities", ["kind"], unique=False)
    op.create_index("ix_activities_kind_status", "activities", ["kind", "status"], unique=False)
    op.create_index(op.f("ix_activities_lead_id"), "activities", ["lead_id"], unique=False)
    op.create_index(op.f("ix_activities_owner_id"), "activities", ["owner_id"], unique=False)
    op.create_index(op.f("ix_activities_project_id"), "activities", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_activities_repeated_from_id"), "activities", ["repeated_from_id"], unique=False
    )
    op.create_index(op.f("ix_activities_site_id"), "activities", ["site_id"], unique=False)
    op.create_index(op.f("ix_activities_starts_on"), "activities", ["starts_on"], unique=False)
    op.create_index(op.f("ix_activities_status"), "activities", ["status"], unique=False)
    op.create_index(op.f("ix_activities_title"), "activities", ["title"], unique=False)
    op.create_index("ix_activities_when", "activities", ["starts_on", "ends_on"], unique=False)
    op.create_table(
        "activity_equipment",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("equipment_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=250), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=60), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("performance_notes", sa.Text(), nullable=True),
        sa.Column("was_essential", sa.Boolean(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f("ck_activity_equipment_ck_activity_equipment_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_equipment_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_activity_equipment_equipment_id_equipment"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_equipment")),
    )
    op.create_index(
        op.f("ix_activity_equipment_activity_id"),
        "activity_equipment",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_equipment_created_at"), "activity_equipment", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activity_equipment_equipment_id"),
        "activity_equipment",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        "ix_activity_equipment_order",
        "activity_equipment",
        ["activity_id", "position"],
        unique=False,
    )
    op.create_table(
        "activity_preparations",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("done_on", sa.Date(), nullable=True),
        sa.Column("responsible_label", sa.String(length=200), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lead_time_days IS NULL OR lead_time_days >= 0",
            name=op.f("ck_activity_preparations_ck_activity_preparations_lead_time_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_preparations_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_preparations")),
    )
    op.create_index(
        op.f("ix_activity_preparations_activity_id"),
        "activity_preparations",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_preparations_category"),
        "activity_preparations",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_preparations_created_at"),
        "activity_preparations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_preparations_due_on"), "activity_preparations", ["due_on"], unique=False
    )
    op.create_index(
        op.f("ix_activity_preparations_is_done"), "activity_preparations", ["is_done"], unique=False
    )
    op.create_index(
        "ix_activity_preparations_order",
        "activity_preparations",
        ["activity_id", "position"],
        unique=False,
    )
    op.create_index(
        "ix_activity_preparations_outstanding",
        "activity_preparations",
        ["activity_id", "is_done"],
        unique=False,
    )
    op.create_table(
        "activity_permits",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("issuer", sa.String(length=250), nullable=True),
        sa.Column("reference", sa.String(length=160), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "not_required",
                "to_apply",
                "applied",
                "granted",
                "refused",
                "expired",
                name="permit_status",
            ),
            nullable=False,
        ),
        sa.Column("applied_on", sa.Date(), nullable=True),
        sa.Column("granted_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("contact", sa.String(length=300), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applied_on IS NULL OR granted_on IS NULL OR granted_on >= applied_on",
            name=op.f("ck_activity_permits_ck_activity_permits_granted_after_applied"),
        ),
        sa.CheckConstraint(
            "cost IS NULL OR cost >= 0",
            name=op.f("ck_activity_permits_ck_activity_permits_cost_not_negative"),
        ),
        sa.CheckConstraint(
            "lead_time_days IS NULL OR lead_time_days >= 0",
            name=op.f("ck_activity_permits_ck_activity_permits_lead_time_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_permits_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_activity_permits_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_permits")),
    )
    op.create_index(
        op.f("ix_activity_permits_activity_id"), "activity_permits", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_permits_created_at"), "activity_permits", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activity_permits_document_id"), "activity_permits", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_permits_expires_on"), "activity_permits", ["expires_on"], unique=False
    )
    op.create_index(
        op.f("ix_activity_permits_issuer"), "activity_permits", ["issuer"], unique=False
    )
    op.create_index(
        "ix_activity_permits_order", "activity_permits", ["activity_id", "position"], unique=False
    )
    op.create_index(
        op.f("ix_activity_permits_status"), "activity_permits", ["status"], unique=False
    )
    op.create_table(
        "activity_photos",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("photograph_id", sa.UUID(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("is_cover", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_photos_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["photograph_id"],
            ["photographs.id"],
            name=op.f("fk_activity_photos_photograph_id_photographs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_photos")),
        sa.UniqueConstraint("activity_id", "photograph_id", name="uq_activity_photos_once"),
    )
    op.create_index(
        op.f("ix_activity_photos_activity_id"), "activity_photos", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_photos_created_at"), "activity_photos", ["created_at"], unique=False
    )
    op.create_index(
        "ix_activity_photos_order", "activity_photos", ["activity_id", "position"], unique=False
    )
    op.create_index(
        op.f("ix_activity_photos_photograph_id"), "activity_photos", ["photograph_id"], unique=False
    )
    op.create_table(
        "activity_costs",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column(
            "category",
            # The type already exists — 0015 created it for expenses, and a
            # cost on an activity is categorised the same way on purpose, so
            # the two add up in a report. create_type=False stops
            # autogenerate's fresh sa.Enum from trying to CREATE TYPE it again.
            postgresql.ENUM(name="expense_category", create_type=False),
            nullable=False,
        ),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=60), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("supplier", sa.String(length=250), nullable=True),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("expense_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_activity_costs_ck_activity_costs_quantity_positive")
        ),
        sa.CheckConstraint(
            "unit_cost >= 0",
            name=op.f("ck_activity_costs_ck_activity_costs_unit_cost_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_costs_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name=op.f("fk_activity_costs_expense_id_expenses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_costs")),
    )
    op.create_index(
        op.f("ix_activity_costs_activity_id"), "activity_costs", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_costs_category"), "activity_costs", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_activity_costs_created_at"), "activity_costs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activity_costs_expense_id"), "activity_costs", ["expense_id"], unique=False
    )
    op.create_index(
        "ix_activity_costs_order", "activity_costs", ["activity_id", "position"], unique=False
    )
    op.create_index(
        op.f("ix_activity_costs_supplier"), "activity_costs", ["supplier"], unique=False
    )
    op.add_column("calendar_events", sa.Column("activity_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_calendar_events_activity_id"), "calendar_events", ["activity_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_calendar_events_activity_id_activities"),
        "calendar_events",
        "activities",
        ["activity_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # At most one cover photograph per activity. A plain unique constraint on
    # (activity_id, is_cover) would permit one cover *and one non-cover*, which
    # is not the rule; the partial index constrains only the covers.
    op.create_index(
        "uq_activity_photos_cover",
        "activity_photos",
        ["activity_id"],
        unique=True,
        postgresql_where=sa.text("is_cover"),
    )

    # Give every existing account the new module.
    #
    # The hub is the institution's shared memory and every *new* account is
    # seeded with it (see app.core.permissions.SEEDED_MODULES). Without this,
    # everybody who signed up before today would find the hub invisible and
    # have to ask an administrator for something the platform gives away
    # freely — which is how a shared record ends up being kept by one person.
    #
    # Administrators are skipped: they hold every module implicitly, and a row
    # for them would make revoking one look meaningful when it is not. The
    # level mirrors DEFAULT_MODULE_ACCESS, and the WHERE NOT EXISTS makes the
    # migration safe to run against a database where somebody has already been
    # granted it by hand.
    op.execute(
        """
        INSERT INTO user_module_access (id, user_id, module, level, note, created_at, updated_at)
        SELECT gen_random_uuid(),
               u.id,
               'activities'::module,
               CASE u.role
                   WHEN 'visitor'    THEN 'viewer'
                   WHEN 'student'    THEN 'contributor'
                   WHEN 'researcher' THEN 'supervisor'
                   ELSE 'viewer'
               END::module_level,
               'Granted when the activity hub was added',
               now(),
               now()
          FROM users u
         WHERE u.role <> 'admin'
           AND NOT EXISTS (
               SELECT 1 FROM user_module_access a
                WHERE a.user_id = u.id AND a.module = 'activities'
           )
        """
    )


def downgrade() -> None:
    # Take back the grants this migration handed out. Left behind, they are
    # rows naming a module the code no longer has — harmless but confusing, and
    # they would collide with the INSERT on a re-upgrade if the note ever
    # changed. Only the ones this migration wrote, identified by their note: a
    # grant somebody made deliberately is theirs to remove.
    op.execute(
        """
        DELETE FROM user_module_access
         WHERE module = 'activities'
           AND note = 'Granted when the activity hub was added'
        """
    )
    op.drop_index("uq_activity_photos_cover", table_name="activity_photos")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_calendar_events_activity_id_activities"), "calendar_events", type_="foreignkey"
    )
    op.drop_index(op.f("ix_calendar_events_activity_id"), table_name="calendar_events")
    op.drop_column("calendar_events", "activity_id")
    op.drop_index(op.f("ix_activity_costs_supplier"), table_name="activity_costs")
    op.drop_index("ix_activity_costs_order", table_name="activity_costs")
    op.drop_index(op.f("ix_activity_costs_expense_id"), table_name="activity_costs")
    op.drop_index(op.f("ix_activity_costs_created_at"), table_name="activity_costs")
    op.drop_index(op.f("ix_activity_costs_category"), table_name="activity_costs")
    op.drop_index(op.f("ix_activity_costs_activity_id"), table_name="activity_costs")
    op.drop_table("activity_costs")
    op.drop_index(op.f("ix_activity_photos_photograph_id"), table_name="activity_photos")
    op.drop_index("ix_activity_photos_order", table_name="activity_photos")
    op.drop_index(op.f("ix_activity_photos_created_at"), table_name="activity_photos")
    op.drop_index(op.f("ix_activity_photos_activity_id"), table_name="activity_photos")
    op.drop_table("activity_photos")
    op.drop_index(op.f("ix_activity_permits_status"), table_name="activity_permits")
    op.drop_index("ix_activity_permits_order", table_name="activity_permits")
    op.drop_index(op.f("ix_activity_permits_issuer"), table_name="activity_permits")
    op.drop_index(op.f("ix_activity_permits_expires_on"), table_name="activity_permits")
    op.drop_index(op.f("ix_activity_permits_document_id"), table_name="activity_permits")
    op.drop_index(op.f("ix_activity_permits_created_at"), table_name="activity_permits")
    op.drop_index(op.f("ix_activity_permits_activity_id"), table_name="activity_permits")
    op.drop_table("activity_permits")
    op.drop_index("ix_activity_preparations_outstanding", table_name="activity_preparations")
    op.drop_index("ix_activity_preparations_order", table_name="activity_preparations")
    op.drop_index(op.f("ix_activity_preparations_is_done"), table_name="activity_preparations")
    op.drop_index(op.f("ix_activity_preparations_due_on"), table_name="activity_preparations")
    op.drop_index(op.f("ix_activity_preparations_created_at"), table_name="activity_preparations")
    op.drop_index(op.f("ix_activity_preparations_category"), table_name="activity_preparations")
    op.drop_index(op.f("ix_activity_preparations_activity_id"), table_name="activity_preparations")
    op.drop_table("activity_preparations")
    op.drop_index("ix_activity_equipment_order", table_name="activity_equipment")
    op.drop_index(op.f("ix_activity_equipment_equipment_id"), table_name="activity_equipment")
    op.drop_index(op.f("ix_activity_equipment_created_at"), table_name="activity_equipment")
    op.drop_index(op.f("ix_activity_equipment_activity_id"), table_name="activity_equipment")
    op.drop_table("activity_equipment")
    op.drop_index("ix_activities_when", table_name="activities")
    op.drop_index(op.f("ix_activities_title"), table_name="activities")
    op.drop_index(op.f("ix_activities_status"), table_name="activities")
    op.drop_index(op.f("ix_activities_starts_on"), table_name="activities")
    op.drop_index(op.f("ix_activities_site_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_repeated_from_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_project_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_owner_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_lead_id"), table_name="activities")
    op.drop_index("ix_activities_kind_status", table_name="activities")
    op.drop_index(op.f("ix_activities_kind"), table_name="activities")
    op.drop_index(op.f("ix_activities_is_public"), table_name="activities")
    op.drop_index(op.f("ix_activities_ends_on"), table_name="activities")
    op.drop_index(op.f("ix_activities_created_at"), table_name="activities")
    op.drop_index(op.f("ix_activities_budget_id"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###

    # Autogenerate writes the CREATE TYPE and never the DROP, so a downgrade
    # leaves the enum types behind and the next upgrade fails on "type already
    # exists". `expense_category` is deliberately absent: it belongs to the
    # management module and dropping it here would take the expenses table's
    # column with it.
    for name in ("activity_kind", "activity_status", "permit_status"):
        op.execute(f"DROP TYPE IF EXISTS {name}")
