"""museum collections module

Revision ID: 8b26338ca156
Revises: 0007_storage_locations
Created: 2026-08-01 06:45:02.497556+00:00

The museum module: collections with their own accession numbering, accessioned
objects, conservation history, exhibitions, loans and environmental readings.

Three enum types already exist and are reused rather than re-declared —
``condition_state``, ``conservation_status`` and ``review_status``. Autogenerate
emits a fresh CREATE TYPE for each, which fails on any database this schema has
ever been applied to.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = "0008_museum"
down_revision: Union[str, None] = "0007_storage_locations"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("accession_pattern", sa.String(length=120), nullable=True),
        sa.Column("accession_prefix", sa.String(length=40), nullable=True),
        sa.Column("accession_sequence", sa.Integer(), nullable=False),
        sa.Column("enforce_pattern", sa.Boolean(), nullable=False),
        sa.Column("institution", sa.String(length=300), nullable=True),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("curator_id", sa.UUID(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["curator_id"],
            ["users.id"],
            name=op.f("fk_collections_curator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_collections_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
    )
    op.create_index(op.f("ix_collections_code"), "collections", ["code"], unique=True)
    op.create_index(op.f("ix_collections_created_at"), "collections", ["created_at"], unique=False)
    op.create_index(op.f("ix_collections_is_public"), "collections", ["is_public"], unique=False)
    op.create_index(op.f("ix_collections_name"), "collections", ["name"], unique=False)
    op.create_index(op.f("ix_collections_owner_id"), "collections", ["owner_id"], unique=False)
    op.create_table(
        "environmental_readings",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("relative_humidity", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("illuminance_lux", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("uv_microwatt_lumen", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "temperature_c IS NOT NULL OR relative_humidity IS NOT NULL OR illuminance_lux IS NOT NULL OR uv_microwatt_lumen IS NOT NULL",
            name=op.f("ck_environmental_readings_ck_environmental_readings_has_a_value"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["storage_locations.id"],
            name=op.f("fk_environmental_readings_location_id_storage_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_environmental_readings_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environmental_readings")),
    )
    op.create_index(
        op.f("ix_environmental_readings_created_at"),
        "environmental_readings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_environmental_readings_location_id"),
        "environmental_readings",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        "ix_environmental_readings_location_time",
        "environmental_readings",
        ["location_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_environmental_readings_recorded_at"),
        "environmental_readings",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_environmental_readings_source"), "environmental_readings", ["source"], unique=False
    )
    op.create_table(
        "exhibitions",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("subtitle", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planned", "in_preparation", "open", "closed", "cancelled", name="exhibition_status"
            ),
            nullable=False,
        ),
        sa.Column("venue", sa.String(length=300), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("opens_on", sa.Date(), nullable=True),
        sa.Column("closes_on", sa.Date(), nullable=True),
        sa.Column("curator", sa.String(length=200), nullable=True),
        sa.Column("curator_id", sa.UUID(), nullable=True),
        sa.Column("is_permanent", sa.Boolean(), nullable=False),
        sa.Column("catalogue_reference", sa.String(length=300), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "opens_on IS NULL OR closes_on IS NULL OR opens_on <= closes_on",
            name=op.f("ck_exhibitions_ck_exhibitions_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["curator_id"],
            ["users.id"],
            name=op.f("fk_exhibitions_curator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["storage_locations.id"],
            name=op.f("fk_exhibitions_location_id_storage_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_exhibitions_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exhibitions")),
    )
    op.create_index(op.f("ix_exhibitions_closes_on"), "exhibitions", ["closes_on"], unique=False)
    op.create_index(op.f("ix_exhibitions_created_at"), "exhibitions", ["created_at"], unique=False)
    op.create_index(op.f("ix_exhibitions_is_public"), "exhibitions", ["is_public"], unique=False)
    op.create_index(op.f("ix_exhibitions_opens_on"), "exhibitions", ["opens_on"], unique=False)
    op.create_index(op.f("ix_exhibitions_owner_id"), "exhibitions", ["owner_id"], unique=False)
    op.create_index(op.f("ix_exhibitions_status"), "exhibitions", ["status"], unique=False)
    op.create_index(op.f("ix_exhibitions_title"), "exhibitions", ["title"], unique=False)
    op.create_table(
        "loans",
        sa.Column("reference", sa.String(length=80), nullable=False),
        sa.Column(
            "direction", sa.Enum("outgoing", "incoming", name="loan_direction"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "approved",
                "declined",
                "in_transit",
                "on_loan",
                "returned",
                "cancelled",
                name="loan_status",
            ),
            nullable=False,
        ),
        sa.Column("counterparty", sa.String(length=300), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("exhibition_id", sa.UUID(), nullable=True),
        sa.Column("requested_on", sa.Date(), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("returned_on", sa.Date(), nullable=True),
        sa.Column("insurance_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("insurance_currency", sa.String(length=3), nullable=True),
        sa.Column("conditions", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "starts_on IS NULL OR ends_on IS NULL OR starts_on <= ends_on",
            name=op.f("ck_loans_ck_loans_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["exhibition_id"],
            ["exhibitions.id"],
            name=op.f("fk_loans_exhibition_id_exhibitions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_loans_owner_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loans")),
    )
    op.create_index(op.f("ix_loans_created_at"), "loans", ["created_at"], unique=False)
    op.create_index(op.f("ix_loans_direction"), "loans", ["direction"], unique=False)
    op.create_index(op.f("ix_loans_ends_on"), "loans", ["ends_on"], unique=False)
    op.create_index(op.f("ix_loans_is_public"), "loans", ["is_public"], unique=False)
    op.create_index(op.f("ix_loans_owner_id"), "loans", ["owner_id"], unique=False)
    op.create_index(op.f("ix_loans_reference"), "loans", ["reference"], unique=True)
    op.create_index(op.f("ix_loans_starts_on"), "loans", ["starts_on"], unique=False)
    op.create_index(op.f("ix_loans_status"), "loans", ["status"], unique=False)
    op.create_table(
        "museum_objects",
        sa.Column("accession_number", sa.String(length=120), nullable=False),
        sa.Column("former_number", sa.String(length=120), nullable=True),
        sa.Column("number_is_legacy", sa.Boolean(), nullable=False),
        sa.Column("part_number", sa.String(length=40), nullable=True),
        sa.Column("object_count", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("object_type", sa.String(length=200), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("period_id", sa.UUID(), nullable=True),
        sa.Column("culture", sa.String(length=200), nullable=True),
        sa.Column("date_from", sa.Integer(), nullable=True),
        sa.Column("date_to", sa.Integer(), nullable=True),
        sa.Column("date_note", sa.String(length=300), nullable=True),
        sa.Column("materials", postgresql.ARRAY(sa.String(length=120)), nullable=True),
        sa.Column("techniques", postgresql.ARRAY(sa.String(length=120)), nullable=True),
        sa.Column("maker", sa.String(length=300), nullable=True),
        sa.Column("inscription", sa.Text(), nullable=True),
        sa.Column("marks", sa.Text(), nullable=True),
        sa.Column("height_mm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("width_mm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("depth_mm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("diameter_mm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("thickness_mm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("weight_g", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("dimension_note", sa.String(length=300), nullable=True),
        sa.Column(
            "condition",
            postgresql.ENUM(name="condition_state", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "conservation_status",
            postgresql.ENUM(name="conservation_status", create_type=False),
            nullable=False,
        ),
        sa.Column("condition_note", sa.Text(), nullable=True),
        sa.Column("last_checked_on", sa.Date(), nullable=True),
        sa.Column("last_checked_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "acquisition_method",
            sa.Enum(
                "excavation",
                "survey",
                "donation",
                "bequest",
                "purchase",
                "exchange",
                "transfer",
                "field_collection",
                "seizure",
                "repatriation",
                "unknown",
                name="acquisition_method",
            ),
            nullable=False,
        ),
        sa.Column("acquisition_date", sa.Date(), nullable=True),
        sa.Column("acquisition_source", sa.String(length=300), nullable=True),
        sa.Column("acquisition_note", sa.Text(), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=True),
        sa.Column("credit_line", sa.String(length=300), nullable=True),
        sa.Column("valuation_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("valuation_currency", sa.String(length=3), nullable=True),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("insurance_reference", sa.String(length=120), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "temporary",
                "accessioned",
                "on_display",
                "in_conservation",
                "on_loan",
                "deaccessioned",
                "missing",
                "destroyed",
                name="object_status",
            ),
            nullable=False,
        ),
        sa.Column("storage_location_id", sa.UUID(), nullable=True),
        sa.Column("home_location_id", sa.UUID(), nullable=True),
        sa.Column("deaccession_date", sa.Date(), nullable=True),
        sa.Column("deaccession_reason", sa.Text(), nullable=True),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("rights_statement", sa.String(length=300), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=80)), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "review_status",
            postgresql.ENUM(name="review_status", create_type=False),
            nullable=False,
        ),
        sa.Column("public_token", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "date_from IS NULL OR date_to IS NULL OR date_from <= date_to",
            name=op.f("ck_museum_objects_ck_museum_objects_date_range"),
        ),
        sa.CheckConstraint(
            "object_count >= 1", name=op.f("ck_museum_objects_ck_museum_objects_count")
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_museum_objects_artifact_id_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["object_categories.id"],
            name=op.f("fk_museum_objects_category_id_object_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_museum_objects_collection_id_collections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_museum_objects_home_location_id_storage_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_checked_by_id"],
            ["users.id"],
            name=op.f("fk_museum_objects_last_checked_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_museum_objects_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["periods.id"],
            name=op.f("fk_museum_objects_period_id_periods"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_museum_objects_storage_location_id_storage_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_museum_objects")),
        sa.UniqueConstraint(
            "collection_id", "accession_number", name="uq_museum_objects_accession"
        ),
    )
    op.create_index(
        op.f("ix_museum_objects_accession_number"),
        "museum_objects",
        ["accession_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_museum_objects_acquisition_date"),
        "museum_objects",
        ["acquisition_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_museum_objects_acquisition_method"),
        "museum_objects",
        ["acquisition_method"],
        unique=False,
    )
    op.create_index(
        op.f("ix_museum_objects_artifact_id"), "museum_objects", ["artifact_id"], unique=True
    )
    op.create_index(
        op.f("ix_museum_objects_category_id"), "museum_objects", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_museum_objects_collection_id"), "museum_objects", ["collection_id"], unique=False
    )
    op.create_index(
        "ix_museum_objects_collection_status",
        "museum_objects",
        ["collection_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_museum_objects_condition"), "museum_objects", ["condition"], unique=False
    )
    op.create_index(
        op.f("ix_museum_objects_conservation_status"),
        "museum_objects",
        ["conservation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_museum_objects_created_at"), "museum_objects", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_museum_objects_culture"), "museum_objects", ["culture"], unique=False)
    op.create_index(
        op.f("ix_museum_objects_date_from"), "museum_objects", ["date_from"], unique=False
    )
    op.create_index(op.f("ix_museum_objects_date_to"), "museum_objects", ["date_to"], unique=False)
    op.create_index(
        op.f("ix_museum_objects_former_number"), "museum_objects", ["former_number"], unique=False
    )
    op.create_index(
        op.f("ix_museum_objects_is_public"), "museum_objects", ["is_public"], unique=False
    )
    op.create_index(
        op.f("ix_museum_objects_object_type"), "museum_objects", ["object_type"], unique=False
    )
    op.create_index(
        op.f("ix_museum_objects_owner_id"), "museum_objects", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_museum_objects_period_id"), "museum_objects", ["period_id"], unique=False
    )
    op.create_index(
        op.f("ix_museum_objects_public_token"), "museum_objects", ["public_token"], unique=True
    )
    op.create_index(
        op.f("ix_museum_objects_review_status"), "museum_objects", ["review_status"], unique=False
    )
    op.create_index(op.f("ix_museum_objects_status"), "museum_objects", ["status"], unique=False)
    op.create_index(
        op.f("ix_museum_objects_storage_location_id"),
        "museum_objects",
        ["storage_location_id"],
        unique=False,
    )
    op.create_index(op.f("ix_museum_objects_title"), "museum_objects", ["title"], unique=False)
    op.create_index("ix_museum_objects_title_lower", "museum_objects", ["title"], unique=False)
    op.create_table(
        "conservation_records",
        sa.Column("museum_object_id", sa.UUID(), nullable=False),
        sa.Column(
            "treatment_type",
            sa.Enum(
                "examination",
                "cleaning",
                "consolidation",
                "stabilisation",
                "reconstruction",
                "mounting",
                "rehousing",
                "analysis",
                "monitoring",
                "other",
                name="treatment_type",
            ),
            nullable=False,
        ),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("conservator", sa.String(length=200), nullable=True),
        sa.Column("conservator_id", sa.UUID(), nullable=True),
        sa.Column(
            "condition_before",
            postgresql.ENUM(name="condition_state", create_type=False),
            nullable=True,
        ),
        sa.Column(
            "condition_after",
            postgresql.ENUM(name="condition_state", create_type=False),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("materials_used", sa.Text(), nullable=True),
        sa.Column("recommendations", sa.Text(), nullable=True),
        sa.Column("next_review_on", sa.Date(), nullable=True),
        sa.Column("hours_spent", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("cost_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conservator_id"],
            ["users.id"],
            name=op.f("fk_conservation_records_conservator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["museum_object_id"],
            ["museum_objects.id"],
            name=op.f("fk_conservation_records_museum_object_id_museum_objects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_conservation_records_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conservation_records")),
    )
    op.create_index(
        op.f("ix_conservation_records_created_at"),
        "conservation_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conservation_records_is_public"),
        "conservation_records",
        ["is_public"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conservation_records_museum_object_id"),
        "conservation_records",
        ["museum_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conservation_records_next_review_on"),
        "conservation_records",
        ["next_review_on"],
        unique=False,
    )
    op.create_index(
        "ix_conservation_records_object_date",
        "conservation_records",
        ["museum_object_id", "performed_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conservation_records_owner_id"), "conservation_records", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_conservation_records_performed_on"),
        "conservation_records",
        ["performed_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conservation_records_treatment_type"),
        "conservation_records",
        ["treatment_type"],
        unique=False,
    )
    op.create_table(
        "exhibition_items",
        sa.Column("exhibition_id", sa.UUID(), nullable=False),
        sa.Column("museum_object_id", sa.UUID(), nullable=False),
        sa.Column("label_text", sa.Text(), nullable=True),
        sa.Column("case_number", sa.String(length=60), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exhibition_id"],
            ["exhibitions.id"],
            name=op.f("fk_exhibition_items_exhibition_id_exhibitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["museum_object_id"],
            ["museum_objects.id"],
            name=op.f("fk_exhibition_items_museum_object_id_museum_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exhibition_items")),
        sa.UniqueConstraint("exhibition_id", "museum_object_id", name="uq_exhibition_items"),
    )
    op.create_index(
        op.f("ix_exhibition_items_created_at"), "exhibition_items", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_exhibition_items_exhibition_id"),
        "exhibition_items",
        ["exhibition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exhibition_items_museum_object_id"),
        "exhibition_items",
        ["museum_object_id"],
        unique=False,
    )
    op.create_table(
        "loan_items",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("museum_object_id", sa.UUID(), nullable=True),
        sa.Column("external_description", sa.Text(), nullable=True),
        sa.Column(
            "condition_out",
            postgresql.ENUM(name="condition_state", create_type=False),
            nullable=True,
        ),
        sa.Column(
            "condition_in",
            postgresql.ENUM(name="condition_state", create_type=False),
            nullable=True,
        ),
        sa.Column("condition_note", sa.Text(), nullable=True),
        sa.Column("insurance_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "museum_object_id IS NOT NULL OR external_description IS NOT NULL",
            name=op.f("ck_loan_items_ck_loan_items_identifies_something"),
        ),
        sa.ForeignKeyConstraint(
            ["loan_id"], ["loans.id"], name=op.f("fk_loan_items_loan_id_loans"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["museum_object_id"],
            ["museum_objects.id"],
            name=op.f("fk_loan_items_museum_object_id_museum_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan_items")),
        sa.UniqueConstraint("loan_id", "museum_object_id", name="uq_loan_items"),
    )
    op.create_index(op.f("ix_loan_items_created_at"), "loan_items", ["created_at"], unique=False)
    op.create_index(op.f("ix_loan_items_loan_id"), "loan_items", ["loan_id"], unique=False)
    op.create_index(
        op.f("ix_loan_items_museum_object_id"), "loan_items", ["museum_object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_loan_items_museum_object_id"), table_name="loan_items")
    op.drop_index(op.f("ix_loan_items_loan_id"), table_name="loan_items")
    op.drop_index(op.f("ix_loan_items_created_at"), table_name="loan_items")
    op.drop_table("loan_items")
    op.drop_index(op.f("ix_exhibition_items_museum_object_id"), table_name="exhibition_items")
    op.drop_index(op.f("ix_exhibition_items_exhibition_id"), table_name="exhibition_items")
    op.drop_index(op.f("ix_exhibition_items_created_at"), table_name="exhibition_items")
    op.drop_table("exhibition_items")
    op.drop_index(op.f("ix_conservation_records_treatment_type"), table_name="conservation_records")
    op.drop_index(op.f("ix_conservation_records_performed_on"), table_name="conservation_records")
    op.drop_index(op.f("ix_conservation_records_owner_id"), table_name="conservation_records")
    op.drop_index("ix_conservation_records_object_date", table_name="conservation_records")
    op.drop_index(op.f("ix_conservation_records_next_review_on"), table_name="conservation_records")
    op.drop_index(
        op.f("ix_conservation_records_museum_object_id"), table_name="conservation_records"
    )
    op.drop_index(op.f("ix_conservation_records_is_public"), table_name="conservation_records")
    op.drop_index(op.f("ix_conservation_records_created_at"), table_name="conservation_records")
    op.drop_table("conservation_records")
    op.drop_index("ix_museum_objects_title_lower", table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_title"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_storage_location_id"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_status"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_review_status"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_public_token"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_period_id"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_owner_id"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_object_type"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_is_public"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_former_number"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_date_to"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_date_from"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_culture"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_created_at"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_conservation_status"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_condition"), table_name="museum_objects")
    op.drop_index("ix_museum_objects_collection_status", table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_collection_id"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_category_id"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_artifact_id"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_acquisition_method"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_acquisition_date"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_accession_number"), table_name="museum_objects")
    op.drop_table("museum_objects")
    op.drop_index(op.f("ix_loans_status"), table_name="loans")
    op.drop_index(op.f("ix_loans_starts_on"), table_name="loans")
    op.drop_index(op.f("ix_loans_reference"), table_name="loans")
    op.drop_index(op.f("ix_loans_owner_id"), table_name="loans")
    op.drop_index(op.f("ix_loans_is_public"), table_name="loans")
    op.drop_index(op.f("ix_loans_ends_on"), table_name="loans")
    op.drop_index(op.f("ix_loans_direction"), table_name="loans")
    op.drop_index(op.f("ix_loans_created_at"), table_name="loans")
    op.drop_table("loans")
    op.drop_index(op.f("ix_exhibitions_title"), table_name="exhibitions")
    op.drop_index(op.f("ix_exhibitions_status"), table_name="exhibitions")
    op.drop_index(op.f("ix_exhibitions_owner_id"), table_name="exhibitions")
    op.drop_index(op.f("ix_exhibitions_opens_on"), table_name="exhibitions")
    op.drop_index(op.f("ix_exhibitions_is_public"), table_name="exhibitions")
    op.drop_index(op.f("ix_exhibitions_created_at"), table_name="exhibitions")
    op.drop_index(op.f("ix_exhibitions_closes_on"), table_name="exhibitions")
    op.drop_table("exhibitions")
    op.drop_index(op.f("ix_environmental_readings_source"), table_name="environmental_readings")
    op.drop_index(
        op.f("ix_environmental_readings_recorded_at"), table_name="environmental_readings"
    )
    op.drop_index("ix_environmental_readings_location_time", table_name="environmental_readings")
    op.drop_index(
        op.f("ix_environmental_readings_location_id"), table_name="environmental_readings"
    )
    op.drop_index(op.f("ix_environmental_readings_created_at"), table_name="environmental_readings")
    op.drop_table("environmental_readings")
    op.drop_index(op.f("ix_collections_owner_id"), table_name="collections")
    op.drop_index(op.f("ix_collections_name"), table_name="collections")
    op.drop_index(op.f("ix_collections_is_public"), table_name="collections")
    op.drop_index(op.f("ix_collections_created_at"), table_name="collections")
    op.drop_index(op.f("ix_collections_code"), table_name="collections")
    op.drop_table("collections")
    # ### end Alembic commands ###

    # Types created here outlive their tables unless dropped, and a later
    # upgrade would then fail with "type already exists".
    for name in (
        "loan_status",
        "loan_direction",
        "exhibition_status",
        "treatment_type",
        "object_status",
        "acquisition_method",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {name}"))
