"""Scope activity entries to a project.

Revision ID: 0003_activity_project
Revises: 0002_initial_schema
Created: 2026-07-31 15:30:52.353896+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = "0003_activity_project"
down_revision: Union[str, None] = "0002_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Denormalised so the activity feed can be read per project without
    # joining through sites and artifacts to reach one — and so entries about
    # a deleted record keep pointing at the project they happened in.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activity_logs", sa.Column("project_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_activity_logs_project_id"), "activity_logs", ["project_id"], unique=False
    )
    op.create_index(
        "ix_activity_logs_project_time", "activity_logs", ["project_id", "created_at"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_activity_logs_project_id_projects"),
        "activity_logs",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_activity_logs_project_id_projects"), "activity_logs", type_="foreignkey"
    )
    op.drop_index("ix_activity_logs_project_time", table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_project_id"), table_name="activity_logs")
    op.drop_column("activity_logs", "project_id")
    # ### end Alembic commands ###
