"""The library: references, the folders they sit in, and what they are about.

``publications`` already existed and finds already cite it, so it is extended
rather than replaced — every citation recorded before now lands *in* the library
rather than beside it.

Revision ID: 0020_library
Revises: 0019_media_folders
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0020_library"
down_revision: Union[str, None] = "0019_media_folders"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library_collections",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_library_collections_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["library_collections.id"],
            name=op.f("fk_library_collections_parent_id_library_collections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library_collections")),
        sa.UniqueConstraint("parent_id", "name", name="uq_library_collections_sibling_name"),
    )
    op.create_index(
        op.f("ix_library_collections_created_at"),
        "library_collections",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_library_collections_is_public"), "library_collections", ["is_public"], unique=False
    )
    op.create_index(
        op.f("ix_library_collections_name"), "library_collections", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_library_collections_owner_id"), "library_collections", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_library_collections_parent_id"), "library_collections", ["parent_id"], unique=False
    )
    # The unique constraint on (parent_id, name) does not catch two folders
    # with the same name at the *top* level: parent_id is NULL there, and two
    # NULLs are never equal. This partial index is what enforces it, and the
    # top of the tree is where folders actually get made.
    op.create_index(
        "uq_library_collections_root_name",
        "library_collections",
        ["name"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "library_collection_items",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["library_collections.id"],
            name=op.f("fk_library_collection_items_collection_id_library_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_library_collection_items_publication_id_publications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "collection_id", "publication_id", name=op.f("pk_library_collection_items")
        ),
    )
    op.create_table(
        "reference_links",
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("museum_object_id", sa.UUID(), nullable=True),
        sa.Column("locator", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_reference_links_artifact_id_artifacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["excavation_contexts.id"],
            name=op.f("fk_reference_links_context_id_excavation_contexts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["museum_object_id"],
            ["museum_objects.id"],
            name=op.f("fk_reference_links_museum_object_id_museum_objects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_reference_links_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_reference_links_publication_id_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_reference_links_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_links")),
    )
    op.create_index(
        op.f("ix_reference_links_artifact_id"), "reference_links", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_reference_links_context_id"), "reference_links", ["context_id"], unique=False
    )
    op.create_index(
        op.f("ix_reference_links_created_at"), "reference_links", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reference_links_museum_object_id"),
        "reference_links",
        ["museum_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_links_project_id"), "reference_links", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_reference_links_publication_id"),
        "reference_links",
        ["publication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_links_site_id"), "reference_links", ["site_id"], unique=False
    )
    op.create_index(
        "ix_reference_links_targets",
        "reference_links",
        ["site_id", "artifact_id", "museum_object_id"],
        unique=False,
    )
    # ``op.add_column`` does not create the type the way ``create_table`` does,
    # so it is created here explicitly. ``checkfirst`` because a re-run after a
    # partial failure would otherwise stop on "type already exists".
    reference_type = sa.Enum(
        "article",
        "book",
        "chapter",
        "thesis",
        "report",
        "conference",
        "archive",
        "dataset",
        "map",
        "webpage",
        "other",
        name="reference_type",
    )
    reference_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "publications",
        sa.Column(
            "reference_type",
            sa.Enum(
                "article",
                "book",
                "chapter",
                "thesis",
                "report",
                "conference",
                "archive",
                "dataset",
                "map",
                "webpage",
                "other",
                name="reference_type",
                create_type=False,
            ),
            # A server default, because this column is NOT NULL and is being
            # added to a table that already has rows in it. Without one the
            # migration fails on any installation that has ever recorded a
            # citation — which is to say, on the ones that matter.
            server_default="article",
            nullable=False,
        ),
    )
    op.add_column("publications", sa.Column("editors", sa.String(length=500), nullable=True))
    op.add_column("publications", sa.Column("series", sa.String(length=300), nullable=True))
    op.add_column("publications", sa.Column("issue", sa.String(length=50), nullable=True))
    op.add_column("publications", sa.Column("edition", sa.String(length=50), nullable=True))
    op.add_column("publications", sa.Column("place", sa.String(length=200), nullable=True))
    op.add_column("publications", sa.Column("institution", sa.String(length=300), nullable=True))
    op.add_column("publications", sa.Column("language", sa.String(length=80), nullable=True))
    op.add_column("publications", sa.Column("accessed_on", sa.Date(), nullable=True))
    op.add_column("publications", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "publications", sa.Column("keywords", postgresql.ARRAY(sa.String(length=80)), nullable=True)
    )
    op.add_column("publications", sa.Column("citation_key", sa.String(length=120), nullable=True))
    op.add_column(
        "publications",
        sa.Column("is_public", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("publications", sa.Column("owner_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_publications_citation_key"), "publications", ["citation_key"], unique=False
    )

    # The defaults were needed to backfill the existing rows and nothing else:
    # from here the model decides, and leaving them in the schema would mean a
    # future change to that default silently disagreeing with the database.
    op.alter_column("publications", "reference_type", server_default=None)
    op.alter_column("publications", "is_public", server_default=None)
    op.create_index(op.f("ix_publications_is_public"), "publications", ["is_public"], unique=False)
    op.create_index(op.f("ix_publications_owner_id"), "publications", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_publications_reference_type"), "publications", ["reference_type"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_publications_owner_id_users"),
        "publications",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_publications_owner_id_users"), "publications", type_="foreignkey")
    op.drop_index(op.f("ix_publications_reference_type"), table_name="publications")
    op.drop_index(op.f("ix_publications_owner_id"), table_name="publications")
    op.drop_index(op.f("ix_publications_is_public"), table_name="publications")
    op.drop_index(op.f("ix_publications_citation_key"), table_name="publications")
    op.drop_column("publications", "owner_id")
    op.drop_column("publications", "is_public")
    op.drop_column("publications", "citation_key")
    op.drop_column("publications", "keywords")
    op.drop_column("publications", "notes")
    op.drop_column("publications", "accessed_on")
    op.drop_column("publications", "language")
    op.drop_column("publications", "institution")
    op.drop_column("publications", "place")
    op.drop_column("publications", "edition")
    op.drop_column("publications", "issue")
    op.drop_column("publications", "series")
    op.drop_column("publications", "editors")
    op.drop_column("publications", "reference_type")
    op.drop_index("ix_reference_links_targets", table_name="reference_links")
    op.drop_index(op.f("ix_reference_links_site_id"), table_name="reference_links")
    op.drop_index(op.f("ix_reference_links_publication_id"), table_name="reference_links")
    op.drop_index(op.f("ix_reference_links_project_id"), table_name="reference_links")
    op.drop_index(op.f("ix_reference_links_museum_object_id"), table_name="reference_links")
    op.drop_index(op.f("ix_reference_links_created_at"), table_name="reference_links")
    op.drop_index(op.f("ix_reference_links_context_id"), table_name="reference_links")
    op.drop_index(op.f("ix_reference_links_artifact_id"), table_name="reference_links")
    op.drop_table("reference_links")
    op.drop_table("library_collection_items")
    op.drop_index("uq_library_collections_root_name", table_name="library_collections")
    op.drop_index(op.f("ix_library_collections_parent_id"), table_name="library_collections")
    op.drop_index(op.f("ix_library_collections_owner_id"), table_name="library_collections")
    op.drop_index(op.f("ix_library_collections_name"), table_name="library_collections")
    op.drop_index(op.f("ix_library_collections_is_public"), table_name="library_collections")
    op.drop_index(op.f("ix_library_collections_created_at"), table_name="library_collections")
    op.drop_table("library_collections")

    # Autogenerate never drops a type it created, so without this a down
    # migration followed by an up fails on "type reference_type already
    # exists" — which only bites during a rollback, the worst possible moment.
    sa.Enum(name="reference_type").drop(op.get_bind(), checkfirst=True)
