"""Folders of files that live somewhere else.

A season produces four hundred gigabytes of raw frames. Uploading all of it is
sometimes right and sometimes absurd — but a catalogue that is silent about it
will be believed to be complete, and the drive will be reformatted by somebody
who checked the archive first. This records the folder rather than the files.

Revision ID: 0019_media_folders
Revises: 0018_activities
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0019_media_folders"
down_revision: Union[str, None] = "0018_activities"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_folders",
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "photographs",
                "drawings",
                "scans",
                "models_3d",
                "survey",
                "documents",
                "raw",
                "other",
                name="media_folder_kind",
            ),
            nullable=False,
        ),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("medium", sa.String(length=300), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=True),
        sa.Column("size_gb", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("recorded_on", sa.Date(), nullable=True),
        sa.Column("is_backed_up", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_media_folders_artifact_id_artifacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["excavation_contexts.id"],
            name=op.f("fk_media_folders_context_id_excavation_contexts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_media_folders_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_media_folders_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_media_folders_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_folders")),
    )
    op.create_index(
        op.f("ix_media_folders_artifact_id"), "media_folders", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_folders_context_id"), "media_folders", ["context_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_folders_created_at"), "media_folders", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_media_folders_is_public"), "media_folders", ["is_public"], unique=False
    )
    op.create_index(op.f("ix_media_folders_kind"), "media_folders", ["kind"], unique=False)
    op.create_index(
        "ix_media_folders_links",
        "media_folders",
        ["project_id", "site_id", "artifact_id"],
        unique=False,
    )
    op.create_index(op.f("ix_media_folders_owner_id"), "media_folders", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_media_folders_project_id"), "media_folders", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_media_folders_site_id"), "media_folders", ["site_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_folders_site_id"), table_name="media_folders")
    op.drop_index(op.f("ix_media_folders_project_id"), table_name="media_folders")
    op.drop_index(op.f("ix_media_folders_owner_id"), table_name="media_folders")
    op.drop_index("ix_media_folders_links", table_name="media_folders")
    op.drop_index(op.f("ix_media_folders_kind"), table_name="media_folders")
    op.drop_index(op.f("ix_media_folders_is_public"), table_name="media_folders")
    op.drop_index(op.f("ix_media_folders_created_at"), table_name="media_folders")
    op.drop_index(op.f("ix_media_folders_context_id"), table_name="media_folders")
    op.drop_index(op.f("ix_media_folders_artifact_id"), table_name="media_folders")
    op.drop_table("media_folders")
    # Autogenerate never drops a type it created, so without this a down
    # migration followed by an up fails on "type media_folder_kind already
    # exists" — which only ever bites in a rollback, which is the worst
    # possible moment.
    sa.Enum(name="media_folder_kind").drop(op.get_bind(), checkfirst=True)
