"""One storage hierarchy, and an append-only register of what moved where.

Revision ID: 0007_storage_locations
Revises: 0006_module_access
Created: 2026-08-01 05:49:28.478416+00:00

``artifacts.storage_location_id`` is added nullable and left empty. The legacy
``current_location`` and ``storage_box`` columns are free text — "Field house,
Room 2, Shelf B" — and parsing them into a tree would mean guessing which words
name a room and which name a shelf. Guessing wrong writes a wrong location into
a heritage register, so both columns are kept as they are and the mapping is
left to a human who knows the building.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = "0007_storage_locations"
down_revision: Union[str, None] = "0006_module_access"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_locations",
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "institution",
                "building",
                "floor",
                "room",
                "cabinet",
                "shelf",
                "drawer",
                "box",
                name="storage_kind",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("display_path", sa.String(length=1200), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("target_temperature_c", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("target_humidity_percent", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("environment_notes", sa.Text(), nullable=True),
        sa.Column("public_token", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "depth >= 0", name=op.f("ck_storage_locations_ck_storage_locations_depth")
        ),
        sa.CheckConstraint(
            "id <> parent_id",
            name=op.f("ck_storage_locations_ck_storage_locations_not_self_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["storage_locations.id"],
            name=op.f("fk_storage_locations_parent_id_storage_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_locations")),
        sa.UniqueConstraint("parent_id", "code", name="uq_storage_locations_sibling_code"),
    )
    op.create_index(
        op.f("ix_storage_locations_created_at"), "storage_locations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_storage_locations_depth"), "storage_locations", ["depth"], unique=False
    )
    op.create_index(
        op.f("ix_storage_locations_is_active"), "storage_locations", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_storage_locations_kind"), "storage_locations", ["kind"], unique=False)
    op.create_index(op.f("ix_storage_locations_name"), "storage_locations", ["name"], unique=False)
    op.create_index(
        op.f("ix_storage_locations_parent_id"), "storage_locations", ["parent_id"], unique=False
    )
    op.create_index(
        "ix_storage_locations_parent_kind", "storage_locations", ["parent_id", "kind"], unique=False
    )
    op.create_index(op.f("ix_storage_locations_path"), "storage_locations", ["path"], unique=False)
    op.create_index("ix_storage_locations_path_prefix", "storage_locations", ["path"], unique=False)
    op.create_index(
        op.f("ix_storage_locations_public_token"),
        "storage_locations",
        ["public_token"],
        unique=True,
    )
    op.create_table(
        "storage_movements",
        sa.Column(
            "resource_type",
            # The type already exists — record_permissions, revisions and the
            # activity log all use it. Re-declaring it would emit a CREATE TYPE
            # that fails on any database this schema has ever been applied to.
            postgresql.ENUM(name="resource_type", create_type=False),
            nullable=False,
        ),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("resource_label", sa.String(length=300), nullable=True),
        sa.Column("from_location_id", sa.UUID(), nullable=True),
        sa.Column("to_location_id", sa.UUID(), nullable=True),
        sa.Column("from_path", sa.String(length=1200), nullable=True),
        sa.Column("to_path", sa.String(length=1200), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "accession",
                "reorganisation",
                "conservation",
                "analysis",
                "exhibition",
                "loan_out",
                "loan_return",
                "excavation",
                "repatriation",
                "disposal",
                "correction",
                "other",
                name="movement_reason",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("moved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("moved_by_id", sa.UUID(), nullable=True),
        sa.Column("moved_by_label", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_location_id IS NOT NULL OR to_location_id IS NOT NULL",
            name=op.f("ck_storage_movements_ck_storage_movements_has_an_end"),
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_storage_movements_from_location_id_storage_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["moved_by_id"],
            ["users.id"],
            name=op.f("fk_storage_movements_moved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_storage_movements_to_location_id_storage_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_movements")),
    )
    op.create_index(
        op.f("ix_storage_movements_created_at"), "storage_movements", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_storage_movements_moved_at"), "storage_movements", ["moved_at"], unique=False
    )
    op.create_index(
        op.f("ix_storage_movements_reason"), "storage_movements", ["reason"], unique=False
    )
    op.create_index(
        "ix_storage_movements_resource",
        "storage_movements",
        ["resource_type", "resource_id", "moved_at"],
        unique=False,
    )
    op.create_index(
        "ix_storage_movements_to_location", "storage_movements", ["to_location_id"], unique=False
    )
    op.add_column("artifacts", sa.Column("storage_location_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_artifacts_storage_location_id"), "artifacts", ["storage_location_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_artifacts_storage_location_id_storage_locations"),
        "artifacts",
        "storage_locations",
        ["storage_location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_artifacts_storage_location_id_storage_locations"), "artifacts", type_="foreignkey"
    )
    op.drop_index(op.f("ix_artifacts_storage_location_id"), table_name="artifacts")
    op.drop_column("artifacts", "storage_location_id")
    op.drop_index("ix_storage_movements_to_location", table_name="storage_movements")
    op.drop_index("ix_storage_movements_resource", table_name="storage_movements")
    op.drop_index(op.f("ix_storage_movements_reason"), table_name="storage_movements")
    op.drop_index(op.f("ix_storage_movements_moved_at"), table_name="storage_movements")
    op.drop_index(op.f("ix_storage_movements_created_at"), table_name="storage_movements")
    op.drop_table("storage_movements")
    op.drop_index(op.f("ix_storage_locations_public_token"), table_name="storage_locations")
    op.drop_index("ix_storage_locations_path_prefix", table_name="storage_locations")
    op.drop_index(op.f("ix_storage_locations_path"), table_name="storage_locations")
    op.drop_index("ix_storage_locations_parent_kind", table_name="storage_locations")
    op.drop_index(op.f("ix_storage_locations_parent_id"), table_name="storage_locations")
    op.drop_index(op.f("ix_storage_locations_name"), table_name="storage_locations")
    op.drop_index(op.f("ix_storage_locations_kind"), table_name="storage_locations")
    op.drop_index(op.f("ix_storage_locations_is_active"), table_name="storage_locations")
    op.drop_index(op.f("ix_storage_locations_depth"), table_name="storage_locations")
    op.drop_index(op.f("ix_storage_locations_created_at"), table_name="storage_locations")
    op.drop_table("storage_locations")
    # ### end Alembic commands ###

    # Enum types outlive the tables that used them unless dropped explicitly,
    # and a later upgrade would then fail with "type already exists".
    for name in ("movement_reason", "storage_kind"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {name}"))
